### ISSUE TITLE
How do you do unroot?

### ISSUE THREAD

**Issue by Khang5687** [Gerriarob/arob#1]
Thanks for the script you provided, I appreciate your work ^^ 
I'm having something to figure out, but first I need to do unroot first, the old aroc project by norilium has it. Can you make one or should I use the script written by norilium?

**Comment by Gerriarob** [comment]
i didnt check the script from norilium, but if you want to unroot you can use root switch, or you can just delete the link and copy the backup  'rm /opt/google/containers/android/system.raw.img' and than 'mv /opt/google/containers/android/system.raw.img.bk /opt/google/containers/android/system.raw.img'   be sure you have the backup in the folder,

i will write a unroot.sh in the next version.
regards Gerri

**Comment by khanhtranngoccva** [comment]
Yes, but I can't reroot. The best solution is to remove /usr/local directories and force a rootfs rebuild, but since I don't know how, I had to reflash Chrome OS.

**Comment by khanhtranngoccva** [comment]
In the meantime, you can edit the "options" list of variables in the bootloader to force a system rebuild. After that, you can reroot without problems.
